config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/create'
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followers
      get :following
    end
  end

  resources :microposts, only: [:create, :destroy]
  #end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/relationships', to: 'relationships#create', as: :relationships
  delete '/relationships/:id', to: 'relationships#destroy', as: :relationship

  # resources :relationship, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home} %>
<% end %>

app/views/shared/_micropost_form.html.erb
<div class="micropost-form">
  <h3>What's up doc ?</h3>

  <%= simple_form_for(@micropost) do |f| %> <!-- @micropost est la liste des microposts de l'user -->
    <%#= render 'shared/error_messages', object: f.object %>
    <%= f.input :content,
            class: 'form_control',
            label: false, placeholder: 'Compose new micropost, add a photo...' %>
    <%= f.submit "Save post", class: "btn" %>

    <div class="image">
      <%= f.input :photo, as: :file, label: false %>
    </div>

  <% end %>
</div>

app/views/shared/_stats.html.erb
<% user = @user ||= current_user %> <!-- la condition n'opère que si @user.nil? -->
<div id="stats">
  <div class="px-3 d-flex justify-content-between">
    <div class="flex-grow-1">
      <div class="text-center border-right">
        <strong><%= link_to user.following.any? ? user.following.count : 0, following_user_path(user) %></strong><br/>
        Following
      </div>
    </div>
    <div class="flex-grow-1">
      <div class="text-center">
        <strong><%= link_to user.followers.any? ? user.followers.count : 0, followers_user_path(user) %></strong><br/>
        Followers
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_info.html.erb
<!-- Remplacer user par current_user p 745-767 -->
  <div class="mb-3 d-flex justify-content-center">
    <%= gravatar_for user %>
    <div class="ml-3">
      <h1 class='username'><%= user.name %></h1>
      <p>Has posted <%= pluralize(user.microposts.count, "micropost") %></p>
  </div>
  </div>

app/views/shared/post_error_messages.html.erb
<% if @micropost.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@micropost.errors.count, "error") %>.
    </div>
    <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>