config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/create'
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followers
      get :following
    end
  end

  resources :microposts, only: [:create, :destroy]
  #end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  post '/relationships', to: 'relationships#create', as: :relationships
  delete '/relationships/:id', to: 'relationships#destroy', as: :relationship

  # resources :relationship, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/" class='link-hover'>Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/" class='link-hover'>Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, class: 'link-hover' %></li>
      <li><%= link_to "Contact", contact_path, class: 'link-hover' %></li>
      <li><a href = "https://news.railstutorial.org/" class='link-hover'>News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
  <div class = "container">
    <div>
      <%= link_to "sample app", root_path, id: "logo" %>
    </div>

    <div class="collapse navbar-collapse d-flex justify-content-end">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path , class: "nav-link" %></li>
        <li><%= link_to "Help", help_path, class: "nav-link" %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: 'nav-link' %></li>
            <li class = "dropdown">
              <%= link_to "Account", '#', class: 'nav-link dropdown-toggle', id: 'dropdownMenuButton', data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
              <ul class = "dropdown-menu" aria-labelledby = "dropdownMenuButton">
                <li ><%= link_to 'Profile', current_user, class: "dropdown-item" %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) , class: "dropdown-item" %></li>
                <li class = "dropdown-divider"></li>
                <li><%= link_to 'Log out', logout_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </li>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container py-5">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>